{% set version = "1.3.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sda
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sda_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sda/sda_{{ version }}.tar.gz
  sha256: 9bc514e6c9a49d81aab6971ab3e5ce1a18e32c3c3a31c43c6f55a924ffa19791

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-corpcor >=1.6.8
    - r-entropy >=1.2.1
    - r-fdrtool >=1.2.15
  run:
    - r-base
    - r-corpcor >=1.6.8
    - r-entropy >=1.2.1
    - r-fdrtool >=1.2.15

test:
  commands:
    - $R -e "library('sda')"           # [not win]
    - "\"%R%\" -e \"library('sda')\""  # [win]

about:
  home: http://strimmerlab.org/software/sda/
  license: GPL-3.0-or-later
  summary: Provides an efficient framework for  high-dimensional linear and diagonal discriminant analysis with  variable selection.  The classifier is trained using James-Stein-type  shrinkage estimators and predictor variables are ranked using  correlation-adjusted t-scores (CAT scores).  Variable selection error  is controlled
    using false non-discovery rates or higher criticism.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
