appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EFePN0Pue57ulcSEnNzk1T6nZAW7tun12SAnJe5sjkkZHnezsWjtriJSrgQDZkn9mNqvZirBvHQbdWaVvwjA5eMtJcG9lLoshhS7T7JvwBV8nPdQwsSqe3OEdvH1tUBA2oIaxRpoRniNyn4ad+/YM6IMADP8ZhmU06DLHE6SGX3y1kYYfqFXNJSD91pivDieDc3hLceFYp8HmZdA+D3p65ZLYM2pvYLaoyF9FIPgaboadh2/WaeBWEQZPYgr8w2lPKWQD9N1JQi4pd/lD2TrxpoV3gqHpG1hrZhi0JSHNZ9sxVRP7DhpB9hcbO3iPMZGWgpeugRmAUl7xsL/eV604QQd23BJTbqOCFhs58D4KvHDq7xvHp3EhPk2BpqV6w+ixSVWHdSn+BLSFC0Rzhp42cKVm9H8yPEdwJbUwj+5+nrACO7o3wIKwSAFApT2ek1aVvygs3b/+zadEcncZbxY2lKsB89InGGVTLCX7HTe8XcnAlHDoHQzzbjaNPK05UA/WVY5ikSX4Ptopxyqoyvn4ZMOc1zDW139sQg8x5Q0XvgY6/rbAO/emMWeiNJghWM+H/LAOR+sPUIY+1t8WttburR+IgYmoooeJo2NsR//HE5d4HfgGHPrBOhdTyXZisGMRNxe9/lyFQm4j9vZJc3qZ9nc6MP2rKH8aVxq+4CV9vI=}
