travis:
  secure:
    BINSTAR_TOKEN: vOoD4hBZn1zVqlUHifA+ahhx+Xw/GUGfYZ1ibpZvsSmBbGxZ2qyAyVmq5F2F1Mu4EMzkVgoAX/qjSmCfv/eNUY+WSErJJVKcuKtJK+YKyILsQHhVQNn7sYPVUC8tAyQpH/yqaMWkfYoY+peR+H/aamlLXaVXLpyDvrVYIb8mQWpnmlC6cMWqHe5kYmz6ByMbrxX6+F2+5MOfHnlNbI44mcGL7uRdRuUGkEOElLq+WWgVj2Vhi1ShIMSkM+pFyImRA8uQoW/vB8j7//irrj77Kx4sfnhSJtfLeBeSL2rcyopFyfmA2RkEMr3RAcoudlXBlrLBOLcKUJnhkqnTyp9xNj3JU9SB50yePToWO0FIppm6xd1ff/9kEazv40sXXWoIfDJ3Z8P1ys63+mtan1AuSjL9sDq6TmkJFVpnPb2DU/ChaHLjLEt2yg+A8Ag3HhK1jfcFreTCao6AKNdMM49Dglvj8BIIfcQVAyjIXkSet8xcAAD4ol6GZ/hHAJvCZ5VYgxoGq4duUuRmxRZst55pEtKW+/Sj6m2ea2Go3QzGmjgF39j75QME0AyLWp9LM5zC1yGgZIv6IFccExcs+SR9/fW6JxtaEcIQcUvtVxTjB0clNIuZvOCNbd2vxB6JF3hx203h5HvEcfeEIWdN93fzInvHFiX4deZ/WTkdR6Mo1yM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
