travis:
  secure:
    BINSTAR_TOKEN: W2z/2winLkCjSOvViLtfOxyhWZY2o/FfrDSwsE63HMEeCRvHrFjetkt+NgRPJx6h7xBTZ90c+dsdPxhNWnlsPaA23OYhNxRD4hp6ZOKFszWz3VYuY1EE/XVqjOuLTCbzV0irNZfy3yL+fpI8qZfb54SAafnHRhjS5nQExNmTpkSGoNHX+l5LQ5zAk7LWiBTzaZt8T8fHbdBmkVFIYnviKi47GpkgCGCUtBLmwoDF5LhaPXq2VuoNuHb/Md7HVj4LgbxMCAYOtQ+VXBekAKpPilzPw2UFHpgac2FGg/MxPuQ/G9wPe8N/KE8Mq/icx4wIp2AKeRAJ7YlTXNvZmoOz2Bb964+ojfWusKKitU0iqOYMAccgQkE+fkDXygzWEeB95+yxQPqU4HIz3Jw34VgtGPjOvBTqWBirD2gNvYfb2inQpo4PiX6wHID4csoUa7rIgK3II6SJpDAUj+y11HYEeJBmOk0r6juwpNknCyJeaeyhGCJFST/T8mjyTqtnwOSLkuaaYOz3sp005meeQXMxarKKUpFjv9Dx4jJVbVTRFf1m+BBjpC0271m3vJ0AYHj/04iw+Q3LSRhiiYV3soFaHVADMGtMr/xwStBE3nrrQtAuqzJxn+7XlxmUIYm5IFZlPSRsQLZFDEyLHVmit1ELXKOWlDHlBo6WsMTjzPWgIik=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
