travis:
  secure:
    BINSTAR_TOKEN: ywJ6EPH6H7fjA2BClbYKKFUkEe3s9wBGLYXMmZGxZXhZLzapdey0nd/Dha4UNWbz1QzJpOfqy4iH3h8OmTfmN2yZOZDM3MyM/KRIw6XAHC4QIuCZhAPck2Cx1E3m4PCkYv4AtgSjgD3PQ9Ka2YBZKnYjrelXC7ynXNFtoZirJDN7+qhDzPzHPWStWj7Gp/krE4Z5vea9fekszrD35uTvrlYxYWmCuvcBqbXC2ge85kFANDGk3sM2FfqPLREYvQw7Coiec60oXhxOa+bAFNW4oUHXxvJ5+Jf5bGtZCGbPM9ImfRwMMZ1D2RhC1PxcM9sjaBj9tyzpJ/GOpDEJu06AQ2P7sJVbc/ox6ZOcEh3AP9+XPCbCVWtGdIOr3UOqMlv5YIuC9ws8D2tdwTvaaNS3Gbh5ddfqgIU3TWeT6wsQu751hckWQQbc1zb74OgmsaP2OuOKtm3vrnxAS+ZCyjWMTg3+r7dZv4I2RSVaiarwMLT7/ohXCCUGsYqB0DEBqbFPfVpmSVoxvx0W8xojdgOTVYrKdiE0W+DeCVTGSiszY7maegY/+2+fc/6Sgc4Xl93x/UYTceHr/X9o41peyXPD5BcFbCW4oc3NqO/4tLbmQYN/aWZ4DhNiuMzAZqT4gGHyu2xk2dSmwIBkeDU6BRO3jfLg3BMiW+IsE1TEqP9MxCs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
